language: c
compiler:
  - gcc
#  - clang
notifications:
  recipients:
    - kenhys@gmail.com
branches:
  only:
    - master
    - develop
before_script:
  - curl --location https://raw.github.com/kenhys/sylpheed-plugin-factory/master/misc/travis/sylpheed.sh | sh
  - curl --location https://github.com/kenhys/sylpheed-plugin-factory/raw/master/misc/travis/sylplugin-factory.sh | sh
  - ./autogen.sh
script:
  - curl --location https://github.com/kenhys/sylpheed-plugin-factory/raw/master/misc/travis/configure.sh | sh
  - make
